### ISSUE TITLE
"doh-client --noverify" encounter error

### ISSUE THREAD

**Issue by luckypoem** [treussart/quart-doh#1]
hi.

yudeMacBook-Air:quart-doh-by-treussart brite$ doh-client --noverify
Traceback (most recent call last):
  File "/usr/local/bin/doh-client", line 11, in <module>
    load_entry_point('quart-doh==0.1.0', 'console_scripts', 'doh-client')()
TypeError: main() missing 1 required positional argument: 'args'
yudeMacBook-Air:quart-doh-by-treussart brite$

how to let doh-client to connect to doh-server?

**Comment by treussart** [comment]
Sorry but now : main(args) 
Use this file instead
https://github.com/treussart/quart-doh/blob/master/quart_doh/client.py
`python quart_doh/client.py  --noverify`
